### ISSUE TITLE
Dependency does not exist on Crates.io

### ISSUE THREAD

**Issue by ppoliani** [ZenGo-X/multi-party-ecdsa#113]
At the moment it is not possible to build the project. The `zeroize: 0.10.x` has been yanked so cargo cannot find it.

Shall we update the crate to the latest version?

**Comment by omershlo** [comment]
thank you @ppoliani , looking into it!

**Comment by ppoliani** [comment]
Thanks @omershlo. I checked the latest version is 1.3.0; however the package is a dep of all the other sub-deps which are currently pointing to Github repos.

**Comment by omershlo** [comment]
Hi, fix is taking some time, 
Please try to work on one of the earlier tags instead of latest.

**Comment by ppoliani** [comment]
@omershlo thanks buddy. Do you mean that there is a version of the lib that doesn't depend on `zeroize`? I'm asking because any version below v1 if [yanked](https://crates.io/crates/zeroize/versions) so I think we'll get the same error.

**Comment by survived** [comment]
Hi @ppoliani, please check if #114 solves the issue - try `v0.4.5` tag

**Comment by survived** [comment]
Hi @ppoliani, thanks for raising the issue. #114 fixes it

**Comment by ppoliani** [comment]
Thank you guys 👍
