### ISSUE TITLE
build fails after change on ZenGo-X/curv

### ISSUE THREAD

**Issue by davfra** [ZenGo-X/multi-party-ecdsa#127]
After [this change](https://github.com/ZenGo-X/curv/commit/b53df44eca2ed6e71025014c979b008621a996bb) on ZenGo-X/curv, multi-party-ecdsa does not build (`cargo build --release --examples`) any more, resulting in the following error message:
```error: failed to select a version for the requirement `ring-algorithm = "^0.2.3"`
candidate versions found which didn't match: 0.4.0
location searched: crates.io index
required by package `class_group v0.5.2 (https://github.com/KZen-networks/class?tag=v0.5.2#6656e421)`
    ... which is depended on by `multi-party-ecdsa v0.6.0 ```

**Comment by omershlo** [comment]
Thanks @davfra ! 
The link to Curv library you pointed to contains the fix to handle ring-algorithm dependency. We will update in the next days the zengo-x libraries that also suffer from this issue - to use the fixed Curv library. 

cc: @elichai , @survived , @MatanHamilis

**Comment by survived** [comment]
`ring-algorithm v0.2.3` was unyanked — `multi-party-ecdsa` builds now without any issues
