### ISSUE TITLE
Yanked v0.7 crypto-mac crate causes build problem

### ISSUE THREAD

**Issue by rimbi** [ZenGo-X/multi-party-ecdsa#135]
I face a problem due to the yanked v0.7 crypto-mac crate
There is this dependency tree causing the problem:
crypto-mac <- hmac <- curv <- multi-party-ecdsa

**Comment by survived** [comment]
Hi @rimbi, we've fixed the problem by releasing `curv v0.7.1` with bumped `hmac`. `multi-party-ecdsa` should be buildable now!
