### ISSUE TITLE
Remove zeroize once num-bigint supports zeroization on drop

### ISSUE THREAD

**Issue by tmpfs** [ZenGo-X/multi-party-ecdsa#148]
The `zeroize` library is currently required for `range_proofs.rs` because `BigInt` from the `num-bigint` backend does not yet support zeroization on drop, once support is added to `num-bigint` the `zeroize` dependency can be completely removed.

Original discussion is [here](https://github.com/ZenGo-X/multi-party-ecdsa/pull/144).

**Comment by survived** [comment]
Closing per discussion in [separate thread](https://github.com/ZenGo-X/multi-party-ecdsa/pull/144#issuecomment-997492108)
