### ISSUE TITLE
Anyone knows how to verify the generated threshold signature in solidity?

### ISSUE THREAD

**Issue by KunPengRen** [ZenGo-X/multi-party-ecdsa#177]
Is it possible to verify the generated signature in solidity code?
Is there some work done this?

**Comment by KunPengRen** [comment]
Extend question？
How to generate the {r,s,v} format  ecdsa signature?

**Comment by KunPengRen** [comment]
the problem is solved, I will add some method soon if someone needs

**Comment by neocho** [comment]
Hey, were you able to recover the public key from local key share by any chance?

**Comment by alexreyes** [comment]
Hey @KunPengRen, how did you retrieve the public key? That's the part I'm currently trying to figure out

**Comment by KunPengRen** [comment]
@alexreyes https://programmer.ink/think/specific-process-of-ethereum-generating-address-from-public-key.html

**Comment by manel1874** [comment]
I am bit confused with the local-sharei.json file that is generated from gg_keygen.rs. I am trying to use it to retrieve the public key to verify the signature.

pk_vec is the public key vector? If that is the case, shouldn't it be in (x,y) format as it is a point in an Elliptic Curve?

Moreover, is keys_linear the share of the private key owned by each party?

**Comment by manel1874** [comment]
I guess the simple answer is that the public key vector is represented in its compressed form.

**Comment by alexreyes** [comment]
@manel1874 Nope I never did get it to consistently work

**Comment by duncancmt** [comment]
I only just started reading this repo, so I have no idea how to parse out the pubkey from the local keystore. However, if you have a signature by the key, you can recover the raw public key from the signature. Given `r`, `s` and the message, compute: https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Public_key_recovery . This is what `ecrecover` in Solidity does under the hood.

**Comment by manel1874** [comment]
Thanks @duncancmt! I recovered a raw public key from the signature elements `(r,s,recid)`. However, the retrieved public key is not equal to any of the possible elements in the `local-sharei.txt`. I compared with `y` (which I believe is the real public key), `y_sum_s` and `pk_vec` (here I summed all three EC points). None of them was equal to the retrieved public key. 

Most probably I am not converting well the hex vector from `local-sharei.txt`. But I am not being able to verify the GG20 generated threshold signature in general (I am using Python).

**Comment by ataki** [comment]
Has anyone here been able to actually issue a signed transaction in a live environment using the gg20 examples? 

This and other threads focus on recovery, and while I've recovered the public key, I haven't been able to issue a correct live transaction.

> I was able to find the solution. So basically the gg20 examples aren't compatible with ethereum. They don't hash the message using keccak256.
> 
> I forked the repo and changed the examples to produce ethereum compatible signatures. https://github.com/narayanprusty/multi-party-ecdsa
> 
> I have also changed the instructions in the readme for gg20 signing. And have added a JS script to recover the address from the signature. I signed the same message multiple times and got the same address from all the signatures.

I'm able to get to the same solution @narayanprusty mentioned, i.e. I'm able to sign different messages multiple times and recover the same address. However, when I sign an actual transaction and issue it on mainnet, I observe that the `from` address is not the same as the address obtained using `recoverAddress`. I'm using `ethers@5.7.1` for both.

As an example, using `recoverAddress` on the keccak256 hash of "hello" gives me `publicKey=0x95e44bab2013F76c4fAF0c65B13B2B94cD61522C`. As is signing a transaction. 
However, the result of injecting that sig into an rpc call to testnet yields an error with the following information returned:

```
transaction: {
    ...
    from: '0x85ea8dE6366768C51d08b484b08a28E93977393F',
    ...
  },
```

**Comment by hcheng826** [comment]
@narayanprusty 
Thanks for your repo! Using your JS script I think I can reconstruct the signer address from the signature. The last piece would be getting the address from public key and verify it's the same.

Do you know how to construct the public key from the `local-sharei.json`? I did a diff on `local-share1.json` and `local-share2.json`, identified that same parts are: `pk_vec`, `paillier_key_vec`, `y_sum_s`, `h1_h2_n_tilde_vec`. Not sure which one(s) should be used. Appreciate it!

**Comment by hcheng826** [comment]
I worked it out for gg20. Sharing my findings

1. `y_sum_s` is the public key: [reference](https://github.com/ZenGo-X/multi-party-ecdsa/blob/9193fb7d42178fe854688b1874a9a7cd61b540c9/src/protocols/multi_party_ecdsa/gg_2020/state_machine/keygen/rounds.rs#L324-L329) 
2. The Ethereum address can be retrieved by ethers ([reference](https://docs.ethers.org/v5/api/utils/address/#utils-computeAddress)). Can refer to my code snippet as well: https://gist.github.com/hcheng826/1de690d61bd408bcbb8bfb99513ab2f2
