### ISSUE TITLE
No zk proof for N_i

### ISSUE THREAD

**Issue by lucky1024** [ZenGo-X/multi-party-ecdsa#188]
In GG18 paper, there is a zk proof for N_i in keygen protocol, but I can't find this in source code.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/45564985/201885709-b25eb88a-579c-456e-8545-bae53f143afa.png">

**Comment by leontiad** [comment]
It is inherreted form [here](https://github.com/ZenGo-X/zk-paillier/blob/master/src/zkproofs/correct_key_ni.rs#L41) if you check the [code](https://github.com/ZenGo-X/multi-party-ecdsa/blob/master/src/protocols/multi_party_ecdsa/gg_2018/party_i.rs)
