### ISSUE TITLE
libsecp256k1 allows overflowing signatures

### ISSUE THREAD

**Issue by joyoFeng** [ZenGo-X/multi-party-ecdsa#192]
Refer to this: https://rustsec.org/advisories/RUSTSEC-2021-0076,  should we need to fix this to upgrade to v0.5 or newer version ?

**Comment by leontiad** [comment]
> Refer to this: https://rustsec.org/advisories/RUSTSEC-2021-0076, should we need to fix this to upgrade to v0.5 or newer version ?

https://github.com/ZenGo-X/multi-party-ecdsa/pull/171
