### ISSUE TITLE
how to get the final public key from the generated keys

### ISSUE THREAD

**Issue by 0xbok** [ZenGo-X/multi-party-ecdsa#202]

**Comment by 0xbok** [comment]
looks like it is `y_sum_s` in the generate key file.

**Comment by ahsan-arif** [comment]
Hi! Is `y_sum_s` the public key? Here is what I did:

1. I generated an address from this y_sum_s vector by using the following code

      `const pkey = ethers.utils.computeAddress("0x" + Buffer.from(y_sum_s).toString("hex"));`

2. Funded the account with 0.2 ETH, and signed the transaction to send 0.001 ETH to some address.

3. When I tried to broadcast the transaction I received an error saying something like  "Insufficient funds for Gas + Value".

Can you please help in this regard?

**Comment by 0xbok** [comment]
yeah, i was probably wrong. I extracted the eth address using `ecrecover`:
- Follow https://github.com/ZenGo-X/multi-party-ecdsa/issues/177#issuecomment-1268398629. In other words, apply this change https://github.com/narayanprusty/multi-party-ecdsa/commit/0aba2995f377c115e68a121baecab6f8e6f06543 by @narayanprusty.
- Compile, and now when you sign using `gg20_sign`, supply the keccak hash as the message.
- The signature will be `r,s,recid`. Get `v=recid+1`.
- Use ecrecover to get the eth address or you can use any web3 library to get recover the public key or the address.

Confirm using multiple signatures that you are getting the same address back.

**Comment by venuswhispers** [comment]
Hello, I am sorry, but whenever creating signatures, it generates different addresses
What about this?

**Comment by venuswhispers** [comment]
Thanks @ahsan-arif
Your post helped me a lot.
thanks again 🤙
