### ISSUE TITLE
Error while compiling on Ubuntu and MacOS

### ISSUE THREAD

**Issue by gagliotti** [ZenGo-X/multi-party-ecdsa#217]
Hi,

I cannot compile multi-party-ecdsa from master branch. The following error occurs:

Compiling multi-party-ecdsa v0.8.1 (/home/martin/multi-party-ecdsa)
error[E0599]: no variant or associated item named `Failure` found for enum `Outcome` in the current scope
   --> examples/gg20_sm_manager.rs:169:26
    |
169 |                 Outcome::Failure((Status::BadRequest, "last seen msg id...
    |                          ^^^^^^^ variant or associated item not found in `Outcome<_, (Status, _), Status>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `multi-party-ecdsa` (example "gg20_sm_manager") due to previous error

I have tried to compile it without success on:
a) Ubuntu 22.04 with rustc 1.73.0 (cc66ad468 2023-10-03)
b) MacOS 11.7.10 with rustc 1.72.1 (d5c2e9c34 2023-09-13).

Any help is welcome.

**Comment by sunxingdi** [comment]
gg20_sm_manager.rs:   change `Outcome::Failure` to `Outcome::Error` 
https://api.rocket.rs/master/rocket/outcome/enum.Outcome.html

**Comment by gagliotti** [comment]
@sunxingdi , thanks! That solves the issue.
